title: A Website for AP CS
author: Claire Zhang
email: cfzhang@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This website was made for the final assignment in AP Computer Science A.
  
# social links
instagram_username: clairefzhang # DO NOT include the @ character, or else the build will fail!
github_username:  clairefz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

https://user-images.githubusercontent.com/65612880/84332424-e8d68280-ab5a-11ea-8a4d-21cb6cae060c.png
